TUTOR_EXAMPLES = [
    "[student name] is a gentle and reserved student who contributes "
    "positively to our Homeroom community. He enjoys interacting with his "
    "peers in the classroom and playground and is happy within his social "
    "environment in the Middle School. It has been pleasing to observe "
    "[student name] taking greater responsibility for his approaches to "
    "learning. He is being encouraged to adopt a more consistent "
    "application to classroom tasks, so that his work always reflects his "
    "best effort.",

    "[student name] is a bright and social member of the Tutor Group who "
    "consistently displays the ROAR tenets of Respect, Opportunity, "
    "Achievement, and Resilience in all facets of her learning. She has "
    "adapted well to the demands of Year 7. In the classroom, she is "
    "engaged and hardworking, and in music and sport, she participates "
    "with enthusiasm. As Year 7 Kerrie House leader, she serves as a "
    "role-model during House events, motivating her peers to do their "
    "best and, in turn, fostering a strong sense of team spirit and "
    "inclusivity during these activities. In Tutor Group, [student name] "
    "is collaborative and open-minded. She both expresses her opinion "
    "and allows others to contribute. Although she loves to socialise, "
    "she channels her energy productively when she needs to. [student "
    "name] should be proud of such a positive start to the year and "
    "should continue to seek out opportunities in Semester 2.",

    "[student name] continues to be a very outgoing, friendly, and "
    "polite member of our Tutorial Group as he moves through Year 12, "
    "though he could be more attentive to the expectations for personal "
    "presentation at school. I am pleased that he is feeling increasingly "
    "motivated in his studies as the year progresses and that he has "
    "found a workable balance between school and social life. The "
    "feedback from his teachers on WiSE suggests that he is making good "
    "progress, and I hope he is following up on their suggestions and "
    "comments. I have enjoyed having [student name] in our Tutorial for "
    "the last three years and seeing him grow as a person over that "
    "time. I wish him the best of luck as he moves towards the Year 12 "
    "exams.",

    "[student name] reflected that she has had a positive start to her "
    "final year at Wesley, with the school formal being a clear "
    "highlight. [student name] has been actively involved in House "
    "activities, including spoons, volleyball, and trivia, making a "
    "valuable contribution to our House spirit. She identified managing "
    "the demanding workload and closely scheduled SACs as a key "
    "challenge this semester. It was encouraging to hear that she has "
    "addressed this by developing a study timetable and making "
    "productive use of her study periods. Looking ahead, [student name] "
    "is keen to continue her involvement in House events and continue "
    "building on her study habits. It has been a delight to have "
    "[student name] in our Tutor Group over the past three years, and I "
    "hope she thoroughly enjoys all the special events leading up to "
    "graduation.",

    "[student name] is a social and enthusiastic member of the Tutor "
    "Group. Throughout Semester 1, [student name] has consistently "
    "displayed the tenets of Opportunity and Resilience as evidenced by "
    "the growth in maturity he has shown transiting from the PYP to the "
    "MYP. Although the academic demands of Year 7 are at times "
    "challenging, he is developing organisational skills to help him "
    "build consistent work habits. [student name]'s true passion is "
    "sports; whether in Physical and Health Education or on the tennis "
    "court, he thrives when able to move freely. For subjects that he "
    "finds more challenging, he is encouraged to seek feedback on his "
    "work and develop a routine for Home Learning tasks. In Tutor "
    "Group, [student name] contributes openly to discussions and "
    "enjoys working collaboratively with his peers. He should be proud "
    "of the way he has embraced new challenges and should keep building "
    "good organisation habits.",
]
